name: chat_sample
description: Chat Sample

version: 0.8.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectycube_sdk: ^2.6.0
  #  connectycube_sdk:
  #    path: ../../flutter-sdk
  shared_preferences: ^2.0.12
  file_picker: ^5.2.11
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  device_info_plus: ^9.0.0
  emoji_picker_flutter: ^1.5.4
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^14.1.1
  connectivity_plus: ^4.0.0
  logging: ^1.0.2
  collection: ^1.17.1
  universal_io: ^2.2.0
  path_provider: ^2.0.8
  package_info_plus: ^4.0.0
  uuid: ^3.0.6
  modal_bottom_sheet: ^3.0.0-pre
  firebase_ui_auth: ^1.5.0
  firebase_auth: ^4.6.3
  flutter_app_badger: ^1.5.0
  firebase_ui_oauth_facebook: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.1
  http: ^1.1.0
  flutter_facebook_auth: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
