name: p2p_call_sample
description: P2P Calls Sample

version: 1.7.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectycube_sdk: ^2.11.3
#  connectycube_sdk:
#    path: ../../flutter-sdk
  shared_preferences: ^2.0.15
  connectycube_flutter_call_kit: ^2.2.4
#  connectycube_flutter_call_kit:
#    path: ../../connectycube-flutter-call-kit/connectycube_flutter_call_kit
  universal_io: ^2.0.4
  web_browser_detect: ^2.0.3
  flutter_background: ^1.2.0
  flutter_speed_dial: ^6.2.0
  permission_handler: ^10.0.1
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true